apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  annotations:
    argocd-image-updater.argoproj.io/image-list: docker.io/nitikjumbo/my_repo           
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/myalias.force-update: "true"
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: mychart
    repoURL: 'https://github.com/Nitik-git/argocd-by-helm.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
