apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: ~/workDir/argo/argocd-image-updater/mychart
    repoURL: ' https://github.com/Nitik-git/argocd-by-helm.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - ~/workDir/argo/argocd-image-updater/mychart/values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
