helm:
  parameters:
  - name: image.name
    value: us-east1-docker.pkg.dev/task-project-374915/argotestrepo/image_my_repo
    forcestring: true
  - name: image.tag
    value: c1.9
    forcestring: true
