helm:
  parameters:
  - name: myalias.image.name
    value: us-east1-docker.pkg.dev/task-project-374915/argotestrepo/image_my_repo
    forcestring: true
  - name: myalias.image.tag
    value: c1.4
    forcestring: true
