apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-argo
  labels:
    app: nginx
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
      - name: artifact-registry
      containers:
      - name: nginx
        image: us-east1-docker.pkg.dev/task-project-374915/argotestrepo/image_my_repo:c1.0
        ports:
        - containerPort: 80
  
